#ifndef slic3r_Layer_hpp_
#define slic3r_Layer_hpp_

#include "libslic3r.h"
#include "BoundingBox.hpp"
#include "Flow.hpp"
#include "SurfaceCollection.hpp"
#include "ExtrusionEntityCollection.hpp"
#include "BoundingBox.hpp"

#include <functional>
#include <optional>

namespace Slic3r {

class ExPolygon;
using ExPolygons = std::vector<ExPolygon>;
class Layer;
using LayerPtrs = std::vector<Layer*>;
class LayerRegion;
using LayerRegionPtrs = std::vector<LayerRegion*>;
class PrintRegion;
class PrintObject;
class Print;

namespace FillAdaptive {
    struct Octree;
};

namespace FillLightning {
    class Generator;
};

namespace sla {
    class IndexedMesh;
};

class LayerRegion
{
public:
    Layer*                      layer()         { return m_layer; }
    const Layer*                layer() const   { return m_layer; }
    const PrintRegion&          region() const  { return *m_region; }

    const SurfaceCollection& get_slices() const { return slices; }

    // Native regional-grid cell metadata. With no assigned cell these accessors describe the whole
    // event layer, as for one region per layer.
    bool        has_cell() const;
    coordf_t    height() const;
    coordf_t    bottom_z() const;
    coordf_t    slice_z() const;
    size_t      cell_index() const;
    LayerRegion       *lower();
    const LayerRegion *lower() const;
    LayerRegion       *upper();
    const LayerRegion *upper() const;
    Layer       *lower_event_layer();
    const Layer *lower_event_layer() const;
    Layer       *upper_event_layer();
    const Layer *upper_event_layer() const;

    void set_cell_metadata(coordf_t bottom_z, coordf_t height, coordf_t slice_z, size_t cell_index,
                           LayerRegion *lower_cell, LayerRegion *upper_cell,
                           Layer *lower_event_layer, Layer *upper_event_layer);

    // The 1-based logical filament that deposits this cell, or 0 for "ask the region's own per-role
    // config". Only a Body Split region with mixed_nozzle_body_fine_skins stamps it, so with the key
    // off every tool and flow lookup is unchanged.
    int  cell_filament_id() const { return m_cell_filament_id; }
    void set_cell_filament_id(int logical_filament_id) { m_cell_filament_id = logical_filament_id; }
    // Same value in the shape PrintRegion::flow() takes: 0-based, or nothing when unstamped.
    std::optional<unsigned int> cell_filament_override() const;
    // Resolve a fallback sparse owner before generating flow and fill parameters.
    std::optional<unsigned int> flow_filament_override(FlowRole role) const;

    // Whether this layer's Feature Split sparse infill stays owned by the region's fine filament
    // (outer_wall_filament_id) rather than its coarse sparse owner (sparse_infill_filament_id).
    // PrintObject::combine_infill() sets every Feature Split layer of a region to true and flips only
    // the top layer of each committed band to false, so an uncombined layer (cadence ratio 1, or a
    // hand-off veto) stays on the fine tool. Read by ToolOrdering only under Feature Split.
    bool feature_split_sparse_fine_owned() const { return m_feature_split_sparse_fine_owned; }
    void set_feature_split_sparse_fine_owned(bool fine_owned) { m_feature_split_sparse_fine_owned = fine_owned; }
    // The same question for sparse infill laid at this height. A band's top layer is coarse owned, but
    // the sparse infill left beside its band (the clearance ring and anything outside the band) is one
    // fine layer thick, thinner than the coarse nozzle can lay, so it stays on the fine filament.
    bool feature_split_sparse_fine_owned_at(double height) const;

    // collection of surfaces generated by slicing the original geometry
    // divided by type top/bottom/internal
    SurfaceCollection           slices;
    // Backed up slices before they are split into top/bottom/internal.
    // Only backed up for multi-region layers or layers with elephant foot compensation.
    //FIXME Review whether not to simplify the code by keeping the raw_slices all the time.
    ExPolygons                  raw_slices;

    // collection of extrusion paths/loops filling gaps
    // These fills are generated by the perimeter generator.
    // They are not printed on their own, but they are copied to this->fills during infill generation.
    ExtrusionEntityCollection   thin_fills;

    // Unspecified fill polygons, used for overhang detection ("ensure vertical wall thickness feature")
    // and for re-starting of infills.
    ExPolygons                  fill_expolygons;
    // collection of surfaces for infill generation
    SurfaceCollection           fill_surfaces;
    // BBS: Unspecified fill polygons, used for interecting when we don't want the infill/perimeter overlap
    ExPolygons                  fill_no_overlap_expolygons;

    // Body Split only: the fuzzy-skin painted part of this cell's slices, with the painted
    // PrintRegion stock Orca would have moved it into. The grid is fixed before fuzzy painting is
    // resolved, so the geometry stays on this cell; make_perimeters() hands each mask to the perimeter
    // generator as a companion region, as stock Orca merges a fuzzy painted sibling into its parent's
    // perimeter call. Empty everywhere else.
    std::vector<std::pair<const PrintRegion*, ExPolygons>> fuzzy_skin_painted_masks;

    // collection of expolygons representing the bridged areas (thus not
    // needing support material)
//    Polygons                    bridged;

    // collection of polylines representing the unsupported bridge edges
    Polylines          			unsupported_bridge_edges;

    // ordered collection of extrusion paths/loops to build all perimeters
    // (this collection contains only ExtrusionEntityCollection objects)
    ExtrusionEntityCollection   perimeters;

    // ordered collection of extrusion paths to fill surfaces
    // (this collection contains only ExtrusionEntityCollection objects)
    ExtrusionEntityCollection   fills;

    Flow    flow(FlowRole role) const;
    Flow    flow(FlowRole role, double layer_height) const;
    Flow    bridging_flow(FlowRole role, bool thick_bridge = false) const;
    Flow    bridging_flow(FlowRole role, bool thick_bridge, double layer_height) const;

    void    slices_to_fill_surfaces_clipped();
    void    prepare_fill_surfaces();
    //BBS
    void    make_perimeters(const SurfaceCollection &slices, const LayerRegionPtrs &compatible_regions, SurfaceCollection* fill_surfaces, ExPolygons* fill_no_overlap, double effective_height = 0.);
    void    process_external_surfaces(const Layer *lower_layer, const Polygons *lower_layer_covered);
    double  infill_area_threshold() const;
    // Trim surfaces by trimming polygons. Used by the elephant foot compensation at the 1st layer.
    void    trim_surfaces(const Polygons &trimming_polygons);
    // Single elephant foot compensation step, used by the elephant foor compensation at the 1st layer.
    // Trim surfaces by trimming polygons (shrunk by an elephant foot compensation step), but don't shrink narrow parts so much that no perimeter would fit.
    void    elephant_foot_compensation_step(const float elephant_foot_compensation_perimeter_step, const Polygons &trimming_polygons);

    void    export_region_slices_to_svg(const char *path) const;
    void    export_region_fill_surfaces_to_svg(const char *path) const;
    // Export to "out/LayerRegion-name-%d.svg" with an increasing index with every export.
    void    export_region_slices_to_svg_debug(const char *name) const;
    void    export_region_fill_surfaces_to_svg_debug(const char *name) const;

    // Is there any valid extrusion assigned to this LayerRegion?
    bool    has_extrusions() const { return ! this->perimeters.entities.empty() || ! this->fills.entities.empty(); }
    //BBS
    void    simplify_infill_extrusion_entity() { simplify_entity_collection(&fills); }
    void    simplify_wall_extrusion_entity() { simplify_entity_collection(&perimeters); }
private:
    void    simplify_entity_collection(ExtrusionEntityCollection* entity_collection);
    void    simplify_path(ExtrusionPath* path);
    void    simplify_multi_path(ExtrusionMultiPath* multipath);
    void    simplify_loop(ExtrusionLoop* loop);

protected:
    friend class Layer;
    friend class PrintObject;

    LayerRegion(Layer *layer, const PrintRegion *region) : m_layer(layer), m_region(region) {}
    ~LayerRegion() {}

private:
    Layer             *m_layer;
    const PrintRegion *m_region;
    coordf_t            m_cell_bottom_z { 0. };
    coordf_t            m_cell_height { 0. };
    coordf_t            m_cell_slice_z { 0. };
    size_t              m_cell_index { 0 };
    int                 m_cell_filament_id { 0 };
    bool                m_feature_split_sparse_fine_owned { false };
    LayerRegion        *m_lower_cell { nullptr };
    LayerRegion        *m_upper_cell { nullptr };
    Layer              *m_lower_event_layer { nullptr };
    Layer              *m_upper_event_layer { nullptr };
};

class Layer
{
public:
    // Sequential index of this layer in PrintObject::m_layers, offsetted by the number of raft layers.
    size_t              id() const          { return m_id; }
    void                set_id(size_t id)   { m_id = id; }
    PrintObject*        object()            { return m_object; }
    const PrintObject*  object() const      { return m_object; }

    Layer              *upper_layer;
    Layer              *lower_layer;
    bool                slicing_errors;
    coordf_t            slice_z;       // Z used for slicing in unscaled coordinates
    coordf_t            print_z;       // Z used for printing in unscaled coordinates
    coordf_t            height;        // layer height in unscaled coordinates
    coordf_t            bottom_z() const { return this->print_z - this->height; }
    // True on the object's first layer, and on every Body Split event layer below the top of a body's
    // first cell when that body's nozzle cannot lay the shared first layer and starts on the bed with
    // a thicker first cell. Those layers print what is on the bed, so they take first-layer speeds,
    // travel, temperatures and acceleration. Otherwise the same as id() == 0.
    bool                in_first_layer_band() const;

    //Extrusions estimated to be seriously malformed, estimated during "Estimating curled extrusions" step. These lines should be avoided during fast travels.
    CurledLines         curled_lines;

    // BBS
    mutable ExPolygons          sharp_tails;
    mutable ExPolygons          cantilevers;
    mutable std::vector<float>  sharp_tails_height;

    // Collection of expolygons generated by slicing the possibly multiple meshes of the source geometry
    // (with possibly differing extruder ID and slicing parameters) and merged.
    // For the first layer, if the Elephant foot compensation is applied, this lslice is uncompensated, therefore
    // it includes the Elephant foot effect, thus it corresponds to the shape of the printed 1st layer.
    // These lslices aka islands are chained by the shortest traverse distance and this traversal
    // order will be applied by the G-code generator to the extrusions fitting into these lslices.
    // These lslices are also used to detect overhangs and overlaps between successive layers, therefore it is important
    // that the 1st lslice is not compensated by the Elephant foot compensation algorithm.
    ExPolygons 				 lslices;
    ExPolygons 				 lslices_extrudable;  // BBS: the extrudable part of lslices used for tree support
    std::vector<BoundingBox> lslices_bboxes;
    // Orca: for separated infills / per-model centering. Aligned with lslices: for each island, the
    // full bounding box of the 3D connected body (across all layers) it belongs to. Populated by
    // PrintObject::infill() only when the feature is used; empty otherwise.
    std::vector<BoundingBox> lslices_separated_component_bboxes;

    // BBS
    ExPolygons              loverhangs;
    BoundingBox             loverhangs_bbox;
    size_t                  region_count() const { return m_regions.size(); }
    const LayerRegion*      get_region(int idx) const { return m_regions[idx]; }
    LayerRegion*            get_region(int idx) { return m_regions[idx]; }
    LayerRegion*            add_region(const PrintRegion *print_region);
    const LayerRegionPtrs&  regions() const { return m_regions; }
    const ExPolygons&       slab_coverage() const { return m_has_slab_coverage ? m_slab_coverage : lslices; }
    bool                    has_slab_coverage() const { return m_has_slab_coverage; }
    LayerRegion            *slab_cell(size_t region_id) {
        return m_has_slab_coverage ? m_slab_cells.at(region_id) : m_regions.at(region_id);
    }
    const LayerRegion      *slab_cell(size_t region_id) const {
        return m_has_slab_coverage ? m_slab_cells.at(region_id) : m_regions.at(region_id);
    }
    void set_slab_coverage(ExPolygons coverage, LayerRegionPtrs cells) {
        m_slab_coverage = std::move(coverage);
        m_slab_cells = std::move(cells);
        m_has_slab_coverage = true;
    }
    // Test whether whether there are any slices assigned to this layer.
    bool                    empty() const;
    void                    make_slices();
    // Backup and restore raw sliced regions if needed.
    //FIXME Review whether not to simplify the code by keeping the raw_slices all the time.
    void                    backup_untyped_slices();
    void                    restore_untyped_slices();
    // To improve robustness of detect_surfaces_type() when reslicing (working with typed slices), see GH issue #7442.
    void                    restore_untyped_slices_no_extra_perimeters();
    // Slices merged into islands, to be used by the elephant foot compensation to trim the individual surfaces with the shrunk merged slices.
    ExPolygons              merged(float offset) const;
    template <class T> bool any_internal_region_slice_contains(const T &item) const {
        for (const LayerRegion *layerm : m_regions) if (layerm->slices.any_internal_contains(item)) return true;
        return false;
    }
    template <class T> bool any_bottom_region_slice_contains(const T &item) const {
        for (const LayerRegion *layerm : m_regions) if (layerm->slices.any_bottom_contains(item)) return true;
        return false;
    }

    // Whether two regions can be printed in a continues perimeter
    static bool             is_perimeter_compatible(const Print& print, const PrintRegion& a, const PrintRegion& b);
    void                    make_perimeters();
    // Phony version of make_fills() without parameters for Perl integration only.
    void                    make_fills() { this->make_fills(nullptr, nullptr); }
    void                    make_fills(FillAdaptive::Octree* adaptive_fill_octree, FillAdaptive::Octree* support_fill_octree,
                                       FillLightning::Generator* lightning_generator = nullptr,
                                       const std::function<bool()> &cancelled = {});
    // Generate fills for a copied candidate surface collection while retaining the source
    // LayerRegion's native flow, spacing, pattern phase and object context. The source layer and
    // region remain untouched; the returned collection owns its generated entities.
    static ExtrusionEntityCollection make_fills_detached(const LayerRegion &source_region,
                                                         const SurfaceCollection &candidate_surfaces,
                                                         std::optional<unsigned int> logical_filament = std::nullopt,
                                                         const std::function<bool()> &cancelled = {},
                                                         bool feature_split_sparse_fine_owned = false);
    Polylines               generate_sparse_infill_polylines_for_anchoring(FillAdaptive::Octree *adaptive_fill_octree,
                                                                           FillAdaptive::Octree *support_fill_octree,
                                                                           FillLightning::Generator* lightning_generator) const;
    // Layer ordinal handed to infill fillers generated for bridge-over-infill anchoring on this event
    // layer. Layers without native cell metadata keep the zero-based object-layer ordinal the
    // parity-dependent patterns consume; hosted cells use their own region-local index.
    size_t                  anchoring_filler_layer_id(const LayerRegion &region) const;
    void 					make_ironing();
    void                    make_contour_z(const sla::IndexedMesh &mesh);

    void                    export_region_slices_to_svg(const char *path) const;
    void                    export_region_fill_surfaces_to_svg(const char *path) const;
    // Export to "out/LayerRegion-name-%d.svg" with an increasing index with every export.
    void                    export_region_slices_to_svg_debug(const char *name) const;
    void                    export_region_fill_surfaces_to_svg_debug(const char *name) const;

    // Is there any valid extrusion assigned to this LayerRegion?
    virtual bool            has_extrusions() const { for (auto layerm : m_regions) if (layerm->has_extrusions()) return true; return false; }

    //BBS
    void simplify_wall_extrusion_path() { for (auto layerm : m_regions) layerm->simplify_wall_extrusion_entity();}
    void simplify_infill_extrusion_path() { for (auto layerm : m_regions) layerm->simplify_infill_extrusion_entity(); }
    //BBS: this function calculate the maximum void grid area of sparse infill of this layer. Just estimated value
    coordf_t get_sparse_infill_max_void_area();

    // FN_HIGHER_EQUAL: the provided object pointer has a Z value >= of an internal threshold.
    // Find the first item with Z value >= of an internal threshold of fn_higher_equal.
    // If no vec item with Z value >= of an internal threshold of fn_higher_equal is found, return vec.size()
    // If the initial idx is size_t(-1), then use binary search.
    // Otherwise search linearly upwards.
    template<typename IteratorType, typename IndexType, typename FN_HIGHER_EQUAL>
    static IndexType idx_higher_or_equal(IteratorType begin, IteratorType end, IndexType idx, FN_HIGHER_EQUAL fn_higher_equal)
    {
        auto size = int(end - begin);
        if (size == 0) {
            idx = 0;
            }
        else if (idx == IndexType(-1)) {
            // First of the batch of layers per thread pool invocation. Use binary search.
            int idx_low = 0;
            int idx_high = std::max(0, size - 1);
            while (idx_low + 1 < idx_high) {
                int idx_mid = (idx_low + idx_high) / 2;
                if (fn_higher_equal(begin[idx_mid]))
                    idx_high = idx_mid;
                else
                    idx_low = idx_mid;
                }
            idx = fn_higher_equal(begin[idx_low]) ? idx_low :
                (fn_higher_equal(begin[idx_high]) ? idx_high : size);
            }
        else {
            // For the other layers of this batch of layers, search incrementally, which is cheaper than the binary search.
            while (int(idx) < size && !fn_higher_equal(begin[idx]))
                ++idx;
            }
        return idx;
    }

    size_t get_extruder_id(unsigned int filament_id) const;

protected:
    friend class PrintObject;
    friend std::vector<Layer*> new_layers(PrintObject*, const std::vector<coordf_t>&);
    friend std::string fix_slicing_errors(PrintObject* object, LayerPtrs&, const std::function<void()>&, int &);

    Layer(size_t id, PrintObject *object, coordf_t height, coordf_t print_z, coordf_t slice_z) :
        upper_layer(nullptr), lower_layer(nullptr), slicing_errors(false),
        slice_z(slice_z), print_z(print_z), height(height),
        m_id(id), m_object(object) {}
    virtual ~Layer();

//BBS: method to simplify support path
    void    simplify_support_entity_collection(ExtrusionEntityCollection* entity_collection);
    void    simplify_support_path(ExtrusionPath* path);
    void    simplify_support_multi_path(ExtrusionMultiPath* multipath);
    void    simplify_support_loop(ExtrusionLoop* loop);

private:
    // Sequential index of layer, 0-based, offsetted by number of raft layers.
    size_t              m_id;
    PrintObject        *m_object;
    LayerRegionPtrs     m_regions;
    ExPolygons          m_slab_coverage;
    LayerRegionPtrs     m_slab_cells;
    bool                m_has_slab_coverage { false };
};

enum SupportInnerType {
    stInnerNormal,
    stInnerTree
};

class SupportLayer : public Layer
{
public:
    // Polygons covered by the supports: base, interface and contact areas.
    // Used to suppress retraction if moving for a support extrusion over these support_islands.
    ExPolygons                  support_islands;
    // Extrusion paths for the support base and for the support interface and contacts.
    ExtrusionEntityCollection   support_fills;
    SupportInnerType            support_type = stInnerNormal;
    // Mixed-nozzle banded support: the body on this layer is laid by the interface nozzle, with
    // interface_nozzle_body_filament (0-based), which PrintObject::generate_support_material() picks
    // once per object with mixed_nozzle_interface_nozzle_body_filament().
    bool                        base_on_interface_nozzle = false;
    unsigned int                interface_nozzle_body_filament = 0;

    // for tree supports
    ExPolygons base_areas;


    // Is there any valid extrusion assigned to this LayerRegion?
    virtual bool                has_extrusions() const { return ! support_fills.empty(); }

    // Zero based index of an interface layer, used for alternating direction of interface / contact layers.
    size_t                      interface_id() const { return m_interface_id; }

    void simplify_support_extrusion_path() { this->simplify_support_entity_collection(&support_fills); }

protected:
    friend class PrintObject;
    friend class TreeSupport;

    // The constructor has been made public to be able to insert additional support layers for the skirt or a wipe tower
    // between the raft and the object first layer.
    SupportLayer(size_t id, size_t interface_id, PrintObject *object, coordf_t height, coordf_t print_z, coordf_t slice_z) :
        Layer(id, object, height, print_z, slice_z), m_interface_id(interface_id), support_type(stInnerNormal) {}
    virtual ~SupportLayer() = default;

    size_t m_interface_id;

    // for tree support
    ExPolygons                                roof_areas;
    ExPolygons                                roof_1st_layer; // the layer just below roof. When working with PolySupport, this layer should be printed with regular material
    ExPolygons                                floor_areas;
    ExPolygons                                roof_gap_areas; // the areas in the gap between support roof and overhang
    enum AreaType { BaseType = 0, RoofType = 1, FloorType = 2, Roof1stLayer = 3 };
    struct AreaGroup
    {
        ExPolygon *area;
        int        type;
        int interface_id = 0;
        bool interface_as_base = false;
        coordf_t   dist_to_top; // mm dist to top
        bool need_infill = false;
        bool need_extra_wall = false;
        AreaGroup(ExPolygon *a, int t, coordf_t d) : area(a), type(t), dist_to_top(d) {}
    };
    std::vector<AreaGroup>                    area_groups;
};

template<typename LayerContainer>
inline std::vector<float> zs_from_layers(const LayerContainer &layers)
{
    std::vector<float> zs;
    zs.reserve(layers.size());
    for (const Layer *l : layers)
        zs.emplace_back((float)l->slice_z);
    return zs;
}

extern BoundingBox get_extents(const LayerRegion &layer_region);
extern BoundingBox get_extents(const LayerRegionPtrs &layer_regions);

}

#endif
